#!/bin/sh

set -ex

. ./job-urls
for job_url in $job_urls
do
  job_name=${job_url##*/}
  ruby build-failures.rb --local $* $job_url > reports/$job_name.failures
done

for job_url in http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc
do
  job_name=${job_url##*/}
  ruby build-failures.rb --local --where triggeredBy=chef-jenkins $* $job_url > reports/$job_name.bumpbot.failures
done

ruby build-failures.rb --local $* $job_urls > reports/all.failures
