#!/bin/sh
ruby jenkins-data.rb http://manhattan.ci.chef.co/job/chef-trigger-release http://manhattan.ci.chef.co/job/chefdk-trigger-release http://wilson.ci.chef.co/job/chef-server-12-trigger-release http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll $*
