#!/usr/bin/env ruby

require "jenkins_pipeline_report"

module JenkinsPipelineReport
  module App
    Cli.parse_options do |opts|
      opts.banner = <<-EOM
        USAGE: ruby #{File.basename(__FILE__)} JOB_URL ...

        Download and cache Jenkins data.

        ruby #{File.basename(__FILE__)} https://manhattan.ci.chef.co/job/chef-trigger-release https://wilson.ci.chef.co/job/chef-server-12-trigger-release

        You must upload your public SSH key to your Jenkins server from ~/.ssh/id_rsa.
      EOM
    end

    Cli.builds(*ARGV).each do |build|
      build.refresh_report
    end
  end
end
